/*
Navicat MySQL Data Transfer

Source Server         : 192.168.72.14
Source Server Version : 80026
Source Host           : 192.168.72.14:3306
Source Database       : nmp_local

Target Server Type    : MYSQL
Target Server Version : 80026
File Encoding         : 65001

Date: 2022-06-02 13:38:57
*/

DROP TABLE IF EXISTS `nmpl_menu`;
CREATE TABLE `nmpl_menu` (
                             `menu_id` bigint NOT NULL AUTO_INCREMENT COMMENT '菜单ID',
                             `menu_name` varchar(50) NOT NULL COMMENT '菜单名称',
                             `parent_menu_id` bigint DEFAULT '-1' COMMENT '父菜单ID',
                             `url` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '请求地址',
                             `is_frame` tinyint DEFAULT '0' COMMENT '是否为外链（1是 0否）',
                             `menu_type` tinyint DEFAULT NULL COMMENT '菜单类型（1目录 2菜单 3按钮）',
                             `menu_status` tinyint DEFAULT '1' COMMENT '菜单状态（1正常 0停用）',
                             `perms_code` varchar(100) DEFAULT NULL,
                             `create_user` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建者',
                             `create_time` datetime(2) DEFAULT CURRENT_TIMESTAMP(2) COMMENT '创建时间',
                             `update_user` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '更新者',
                             `update_time` datetime(2) DEFAULT CURRENT_TIMESTAMP(2) ON UPDATE CURRENT_TIMESTAMP(2) COMMENT '更新时间',
                             `remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '备注',
                             `is_exist` tinyint DEFAULT '1' COMMENT '1正常 0删除',
                             `icon` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '前端按钮',
                             `permission` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0' COMMENT '权限标识',
                             `component` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '前端组件信息',
                             PRIMARY KEY (`menu_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='菜单权限表';

-- ----------------------------
-- Records of nmpl_menu
-- ----------------------------
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (1, '用户权限管理', -1, '/userCenter', 0, 0, 1, NULL, NULL, 1, 'user', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (2, '角色管理', 1, '/role', 0, 1, 1, 'sys:role:query', NULL, 1, '', '0', 'user/role');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (3, '新建角色', 2, NULL, 0, 2, 1, 'sys:role:save', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (4, '删除角色', 2, NULL, 0, 2, 1, 'sys:role:delete', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (5, '编辑角色', 2, NULL, 0, 2, 1, 'sys:role:update', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (6, '用户管理', 1, '/user', 0, 1, 1, 'sys:user:query', NULL, 1, '', '0', 'user');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (7, '新建用户', 6, NULL, 0, 2, 1, 'sys:user:save', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (8, '删除用户', 6, NULL, 0, 2, 1, 'sys:user:delete', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (9, '编辑用户', 6, NULL, 0, 2, 1, 'sys:user:update', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (10, '运营商管理', -1, '/guideindex', 0, 0, 1, '', NULL, 1, 'guide', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (11, '运营商管理', 10, '/guide', 0, 1, 1, 'sys:operator:query', NULL, 1, '', '0', 'guide');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (12, '新增运营商', 11, NULL, 0, 2, 1, 'sys:operator:save', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (13, '修改运营商', 11, NULL, 0, 2, 1, 'sys:operator:update', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (14, '删除运营商', 11, NULL, 0, 2, 1, 'sys:operator:delete', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (17, '区域管理', -1, '/area', 0, 0, 1, NULL, NULL, 1, 'add-location', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (18, '大区管理', 17, '/area/max', 0, 1, 1, 'sys:region:query', NULL, 1, '', '0', 'area/max');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (19, '小区管理', 17, '/area/min', 0, 1, 1, 'sys:village:query', NULL, 1, '', '0', 'area/min');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (20, '新建大区', 18, NULL, 0, 2, 1, 'sys:region:save', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (21, '删除大区', 18, NULL, 0, 2, 1, 'sys:region:delete', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (23, '编辑大区', 18, NULL, 0, 2, 1, 'sys:region:update', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (24, '新建小区', 19, NULL, 0, 2, 1, 'sys:village:save', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (25, '删除小区', 19, NULL, 0, 2, 1, 'sys:village:delete', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (27, '编辑小区', 19, NULL, 0, 2, 1, 'sys:village:update', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (28, '节点管理', -1, '/node', 0, 0, 1, NULL, NULL, 1, 'more-filled', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (29, '基站管理', 28, '/node/station', 0, 1, 1, 'sys:station:query', NULL, 1, '', '0', 'node/station');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (30, '密钥中心管理', 28, '/node/dispenser', 0, 1, 1, 'sys:dispenser:query', NULL, 1, '', '0', 'node/dispenser');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (31, '密钥生成管理', 28, '/node/generate', 0, 1, 1, 'sys:generator:query', NULL, 1, '', '0', 'node/generate');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (32, '缓存机管理', 28, '/node/cache', 0, 1, 1, 'sys:cache:query', NULL, 1, '', '0', 'node/cache');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (33, '新建基站', 29, NULL, 0, 2, 1, 'sys:station:save', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (34, '删除基站', 29, NULL, 0, 2, 1, 'sys:station:delete', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (36, '编辑基站', 29, NULL, 0, 2, 1, 'sys:station:update', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (37, '新建密钥中心', 30, NULL, 0, 2, 1, 'sys:dispenser:save', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (38, '删除密钥中心', 30, NULL, 0, 2, 1, 'sys:dispenser:delete', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (40, '编辑密钥中心', 30, NULL, 0, 2, 1, 'sys:dispenser:update', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (41, '新建生成机', 31, NULL, 0, 2, 1, 'sys:generator:save', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (42, '删除生成机', 31, NULL, 0, 2, 1, 'sys:generator:delete', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (44, '编辑生成机', 31, NULL, 0, 2, 1, 'sys:generator:update', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (45, '新增缓存机', 32, NULL, 0, 2, 1, 'sys:cache:save', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (46, '删除缓存机', 32, NULL, 0, 2, 1, 'sys:cache:delete', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (48, '编辑缓存机', 32, NULL, 0, 2, 1, 'sys:cache:update', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (49, '链路管理', -1, '/linkindex', 0, 0, 1, NULL, NULL, 1, 'operation', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (50, '链路管理', 49, '/link', 0, 1, 1, 'sys:link:query', NULL, 1, '', '0', 'link');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (51, '新建链路', 50, NULL, 0, 2, 1, 'sys:link:save', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (52, '删除链路', 50, NULL, 0, 2, 1, 'sys:link:delete', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (54, '编辑链路', 50, NULL, 0, 2, 1, 'sys:link:update', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (55, '路由管理', -1, '/routeindex', 0, 0, 1, NULL, NULL, 1, 'help', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (56, '路由管理', 55, '/route', 0, 1, 1, 'sys:route:query', NULL, 1, '', '0', 'route');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (57, '新建路由', 56, NULL, 0, 2, 1, 'sys:route:save', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (58, '删除路由', 56, NULL, 0, 2, 1, 'sys:route:delete', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (60, '编辑路由', 56, NULL, 0, 2, 1, 'sys:route:update', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (61, '系统设置', -1, '/setting', 0, 0, 1, NULL, NULL, 1, 'setting', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (62, '参数配置', 61, '/setting/params', 0, 1, 1, 'sys:parm:query', NULL, 1, '', '1', 'setting/params');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (63, '权限菜单', 61, '/setting/auth', 0, 1, 1, 'sys:power:query', NULL, 1, '', '0', 'setting/auth');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (64, '恢复默认参数', 62, NULL, 0, 2, 1, 'sys:parm:reset', NULL, 1, '', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (65, '删除参数', 62, NULL, 0, 2, 1, 'sys:parm:delete', NULL, 1, '', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (67, '编辑参数', 62, NULL, 0, 2, 1, 'sys:parm:update', NULL, 1, '', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (68, '同步参数', 62, NULL, 0, 2, 1, 'sys:parm:synchro', NULL, 1, '', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (70, '状态监控', -1, '/monitorindex', 0, 0, 1, NULL, NULL, 1, 'cpu', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (71, '状态监控', 70, '/monitornew', 0, 1, 1, 'sys:monitor:query,sys:monitor:totalload', NULL, 1, '', '0', 'monitor');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (73, '信令管理', -1, '/signalindex', 0, 0, 1, NULL, NULL, 1, 'data-analysis', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (74, '信令上报', 73, '/signal', 0, 1, 1, 'sys:sign:query,sys:sign:selectDeviceIds,sys:sign:deviceIds', NULL, 1, '', '1', 'signal');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (77, '清空', 74, NULL, 0, 2, 1, 'sys:sign:clear', NULL, 1, '', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (78, '导出文件', 74, NULL, 0, 2, 1, 'sys:sign:export', NULL, 1, '', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (79, '日志管理', -1, '/log', 0, 0, 1, NULL, NULL, 1, 'notification', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (80, '登录日志', 79, '/log/login', 0, 1, 1, 'sys:loginLog:query', NULL, 1, '', '0', 'log/login');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (81, '操作日志', 79, '/log/operate', 0, 1, 1, 'sys:operateLog:query', NULL, 1, '', '0', 'log/operate');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (82, '系统日志', 79, '/log/system', 0, 1, 1, 'sys:sysLog:query', NULL, 1, '', '0', 'log/system');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (86, '统计管理', -1, '/statistics', 0, 0, 1, NULL, NULL, 1, 'monitor', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (87, '基站统计数据', 86, '/statistics/station', 0, 1, 1, 'sys:stationData:query', NULL, 1, '', '0', 'statistics/station');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (88, '密钥中心统计数据', 86, '/statistics/dispenser', 0, 1, 1, 'sys:dispenserData:query', NULL, 1, '', '0', 'statistics/dispenser');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (89, '生成机统计数据', 86, '/statistics/generate', 0, 1, 1, 'sys:generatorData:query', NULL, 1, '', '0', 'statistics/generate');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (90, '缓存机统计数据', 86, '/statistics/cache', 0, 1, 1, 'sys:cacheData:query', NULL, 1, '', '0', 'statistics/cache');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (95, '话单管理', -1, '/ticketindex', 0, 0, 1, NULL, NULL, 1, 'iphone', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (96, '话单上报', 95, '/ticket', 0, 1, 1, 'sys:bill:query', NULL, 1, '', '1', 'ticket');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (98, '版本管理', -1, '/versionindex', 0, 0, 1, NULL, NULL, 1, 'warning', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (99, '版本列表', 98, '/version', 0, 1, 1, 'sys:version:fileList,sys:version:list', NULL, 1, '', '1', 'version');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (100, '新建版本', 99, NULL, 0, 2, 1, 'sys:version:save', NULL, 1, '', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (101, '上传版本文件', 99, NULL, 0, 2, 1, 'sys:version:import', NULL, 1, '', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (102, '删除版本文件', 99, NULL, 0, 2, 1, 'sys:version:deleteFile', NULL, 1, '', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (103, '推送设备', 99, NULL, 0, 2, 1, 'sys:version:push', NULL, 1, '', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (104, '启动', 99, NULL, 0, 2, 1, 'sys:version:start', NULL, 1, '', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (105, '详情', 99, NULL, 0, 2, 1, 'sys:version:detail', NULL, 1, '', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (116, '修改用户密码(更多)', 6, NULL, 0, 2, 1, 'sys:user:changePasswd', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (118, '信令启停', 74, NULL, 0, 2, 1, 'sys:sign:track', NULL, 1, '', '1', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (119, '离线分发机认证放号', -1, '/outlinedispenserindex', 0, 0, 1, NULL, NULL, 1, 'collection', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (120, '离线分发机认证放号', 119, '/outlinedispenser', 0, 1, 1, 'sys:sorter:query', NULL, 1, '', '0', 'outlinedispenser');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (121, '新建设备', 120, NULL, 0, 2, 1, 'sys:sorter:insert', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (122, '编辑', 120, NULL, 0, 2, 1, 'sys:sorter:modify', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (124, '删除', 120, NULL, 0, 2, 1, 'sys:sorter:delete', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (125, '导入文件', 120, NULL, 0, 2, 1, 'sys:sorter:upload', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (126, '一体机认证放号', -1, '/allinoneindex', 0, 0, 1, NULL, NULL, 1, 'credit-card', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (127, '一体机认证放号', 126, '/allinone', 0, 1, 1, 'sys:pc:query', NULL, 1, '', '0', 'allinone');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (128, '新建设备', 127, NULL, 0, 2, 1, 'sys:pc:insert', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (129, '删除', 127, NULL, 0, 2, 1, 'sys:pc:delete', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (131, '编辑', 127, NULL, 0, 2, 1, 'sys:pc:modify', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (132, '导入文件', 127, NULL, 0, 2, 1, 'sys:pc:upload', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (133, '主备管理', 28, '/node/mainbackup', 0, 1, 1, 'sys:deviceExtra:query', NULL, 1, '', '0', 'node/mainbackup');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (134, '新建主备', 133, NULL, 0, 2, 1, 'sys:deviceExtra:save', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (135, '编辑主备', 133, NULL, 0, 2, 1, 'sys:deviceExtra:update', NULL, 1, '', '0', '');
INSERT INTO `nmpl_menu` (`menu_id`, `menu_name`, `parent_menu_id`, `url`, `is_frame`, `menu_type`, `menu_status`, `perms_code`, `remark`, `is_exist`,`icon`,`permission`,`component`) VALUES (136, '删除主备', 133, NULL, 0, 2, 1, 'sys:deviceExtra:delete', NULL, 1, '', '0', '');


