server:
  port: 8008

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 500
    lettuce:
      pool:
        min-idle: 0
        max-active: 100
        max-wait: -1
        max-idle: 8

  application:
    name: UserCenter
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/user_center_in             # 数据库名称
    username: root
    password: Jzsg@2021
    druid:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

logging:
  file:
    path: ./logs
  level:
    com.jzsg: info

app:
  handleType: 1
  flowtype: 0
  name: userCenterProd
  id: UC020
  port: 9120
  timeout: 5000
  innerUrl: http://127.0.0.1:8008
  outerUrl: http://127.0.0.1:8009