server:
  port: 8003

spring:
  redis:
    database: 0
    host: 192.168.72.230
    port: 6379
    password: 123456
    timeout: 500
    lettuce:
      pool:
        min-idle: 0
        max-active: 100
        max-wait: -1
        max-idle: 8

  application:
    name: InformCentralApplication
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.72.230:3306/nmp_local              # 数据库名称
    username: root
    password: Jzsg@2021
    druid:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://localhost:7002/eureka/
  instance:
    instance-id: InformCentralApplication
    prefer-ip-address: true     #访问路径可以显示IP地址     
 
info: 
  app.name: InformCentralApplication
  company.name: www.atjzsg.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
logging:
  file:
    path: ./logs
  level:
    com.jzsg: info