// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.matrictime.network.netty.protocol.message;

public final class MessageBase {
  private MessageBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes version = 1;</code>
     * @return The version.
     */
    com.google.protobuf.ByteString getVersion();

    /**
     * <code>int32 resv = 34;</code>
     * @return The resv.
     */
    int getResv();

    /**
     * <code>int32 uMsgType = 999;</code>
     * @return The uMsgType.
     */
    int getUMsgType();

    /**
     * <code>int32 uTotalLen = 980;</code>
     * @return The uTotalLen.
     */
    int getUTotalLen();

    /**
     * <code>int32 dstRID = 121;</code>
     * @return The dstRID.
     */
    int getDstRID();

    /**
     * <code>int32 srcRID = 234;</code>
     * @return The srcRID.
     */
    int getSrcRID();

    /**
     * <code>int32 uIndex = 112;</code>
     * @return The uIndex.
     */
    int getUIndex();

    /**
     * <code>int32 uEncType = 111;</code>
     * @return The uEncType.
     */
    int getUEncType();

    /**
     * <code>int32 uEncRate = 32;</code>
     * @return The uEncRate.
     */
    int getUEncRate();

    /**
     * <code>int32 checkSum = 12;</code>
     * @return The checkSum.
     */
    int getCheckSum();

    /**
     * <code>string reqData = 123;</code>
     * @return The reqData.
     */
    java.lang.String getReqData();
    /**
     * <code>string reqData = 123;</code>
     * @return The bytes for reqData.
     */
    com.google.protobuf.ByteString
        getReqDataBytes();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    public Message() {
      version_ = com.google.protobuf.ByteString.EMPTY;
      reqData_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.matrictime.network.netty.protocol.message.MessageBase.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.matrictime.network.netty.protocol.message.MessageBase.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.matrictime.network.netty.protocol.message.MessageBase.Message.class, com.matrictime.network.netty.protocol.message.MessageBase.Message.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString version_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getVersion() {
      return version_;
    }

    public static final int RESV_FIELD_NUMBER = 34;
    private int resv_ = 0;
    /**
     * <code>int32 resv = 34;</code>
     * @return The resv.
     */
    @java.lang.Override
    public int getResv() {
      return resv_;
    }

    public static final int UMSGTYPE_FIELD_NUMBER = 999;
    private int uMsgType_ = 0;
    /**
     * <code>int32 uMsgType = 999;</code>
     * @return The uMsgType.
     */
    @java.lang.Override
    public int getUMsgType() {
      return uMsgType_;
    }

    public static final int UTOTALLEN_FIELD_NUMBER = 980;
    private int uTotalLen_ = 0;
    /**
     * <code>int32 uTotalLen = 980;</code>
     * @return The uTotalLen.
     */
    @java.lang.Override
    public int getUTotalLen() {
      return uTotalLen_;
    }

    public static final int DSTRID_FIELD_NUMBER = 121;
    private int dstRID_ = 0;
    /**
     * <code>int32 dstRID = 121;</code>
     * @return The dstRID.
     */
    @java.lang.Override
    public int getDstRID() {
      return dstRID_;
    }

    public static final int SRCRID_FIELD_NUMBER = 234;
    private int srcRID_ = 0;
    /**
     * <code>int32 srcRID = 234;</code>
     * @return The srcRID.
     */
    @java.lang.Override
    public int getSrcRID() {
      return srcRID_;
    }

    public static final int UINDEX_FIELD_NUMBER = 112;
    private int uIndex_ = 0;
    /**
     * <code>int32 uIndex = 112;</code>
     * @return The uIndex.
     */
    @java.lang.Override
    public int getUIndex() {
      return uIndex_;
    }

    public static final int UENCTYPE_FIELD_NUMBER = 111;
    private int uEncType_ = 0;
    /**
     * <code>int32 uEncType = 111;</code>
     * @return The uEncType.
     */
    @java.lang.Override
    public int getUEncType() {
      return uEncType_;
    }

    public static final int UENCRATE_FIELD_NUMBER = 32;
    private int uEncRate_ = 0;
    /**
     * <code>int32 uEncRate = 32;</code>
     * @return The uEncRate.
     */
    @java.lang.Override
    public int getUEncRate() {
      return uEncRate_;
    }

    public static final int CHECKSUM_FIELD_NUMBER = 12;
    private int checkSum_ = 0;
    /**
     * <code>int32 checkSum = 12;</code>
     * @return The checkSum.
     */
    @java.lang.Override
    public int getCheckSum() {
      return checkSum_;
    }

    public static final int REQDATA_FIELD_NUMBER = 123;
    @SuppressWarnings("serial")
    private volatile java.lang.Object reqData_ = "";
    /**
     * <code>string reqData = 123;</code>
     * @return The reqData.
     */
    @java.lang.Override
    public java.lang.String getReqData() {
      java.lang.Object ref = reqData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqData_ = s;
        return s;
      }
    }
    /**
     * <code>string reqData = 123;</code>
     * @return The bytes for reqData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReqDataBytes() {
      java.lang.Object ref = reqData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!version_.isEmpty()) {
        output.writeBytes(1, version_);
      }
      if (checkSum_ != 0) {
        output.writeInt32(12, checkSum_);
      }
      if (uEncRate_ != 0) {
        output.writeInt32(32, uEncRate_);
      }
      if (resv_ != 0) {
        output.writeInt32(34, resv_);
      }
      if (uEncType_ != 0) {
        output.writeInt32(111, uEncType_);
      }
      if (uIndex_ != 0) {
        output.writeInt32(112, uIndex_);
      }
      if (dstRID_ != 0) {
        output.writeInt32(121, dstRID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reqData_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 123, reqData_);
      }
      if (srcRID_ != 0) {
        output.writeInt32(234, srcRID_);
      }
      if (uTotalLen_ != 0) {
        output.writeInt32(980, uTotalLen_);
      }
      if (uMsgType_ != 0) {
        output.writeInt32(999, uMsgType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!version_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, version_);
      }
      if (checkSum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, checkSum_);
      }
      if (uEncRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(32, uEncRate_);
      }
      if (resv_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(34, resv_);
      }
      if (uEncType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(111, uEncType_);
      }
      if (uIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(112, uIndex_);
      }
      if (dstRID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(121, dstRID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reqData_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(123, reqData_);
      }
      if (srcRID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(234, srcRID_);
      }
      if (uTotalLen_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(980, uTotalLen_);
      }
      if (uMsgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(999, uMsgType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.matrictime.network.netty.protocol.message.MessageBase.Message)) {
        return super.equals(obj);
      }
      com.matrictime.network.netty.protocol.message.MessageBase.Message other = (com.matrictime.network.netty.protocol.message.MessageBase.Message) obj;

      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (getResv()
          != other.getResv()) return false;
      if (getUMsgType()
          != other.getUMsgType()) return false;
      if (getUTotalLen()
          != other.getUTotalLen()) return false;
      if (getDstRID()
          != other.getDstRID()) return false;
      if (getSrcRID()
          != other.getSrcRID()) return false;
      if (getUIndex()
          != other.getUIndex()) return false;
      if (getUEncType()
          != other.getUEncType()) return false;
      if (getUEncRate()
          != other.getUEncRate()) return false;
      if (getCheckSum()
          != other.getCheckSum()) return false;
      if (!getReqData()
          .equals(other.getReqData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + RESV_FIELD_NUMBER;
      hash = (53 * hash) + getResv();
      hash = (37 * hash) + UMSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getUMsgType();
      hash = (37 * hash) + UTOTALLEN_FIELD_NUMBER;
      hash = (53 * hash) + getUTotalLen();
      hash = (37 * hash) + DSTRID_FIELD_NUMBER;
      hash = (53 * hash) + getDstRID();
      hash = (37 * hash) + SRCRID_FIELD_NUMBER;
      hash = (53 * hash) + getSrcRID();
      hash = (37 * hash) + UINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getUIndex();
      hash = (37 * hash) + UENCTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getUEncType();
      hash = (37 * hash) + UENCRATE_FIELD_NUMBER;
      hash = (53 * hash) + getUEncRate();
      hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
      hash = (53 * hash) + getCheckSum();
      hash = (37 * hash) + REQDATA_FIELD_NUMBER;
      hash = (53 * hash) + getReqData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.matrictime.network.netty.protocol.message.MessageBase.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.matrictime.network.netty.protocol.message.MessageBase.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.matrictime.network.netty.protocol.message.MessageBase.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.matrictime.network.netty.protocol.message.MessageBase.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.matrictime.network.netty.protocol.message.MessageBase.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.matrictime.network.netty.protocol.message.MessageBase.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.matrictime.network.netty.protocol.message.MessageBase.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.matrictime.network.netty.protocol.message.MessageBase.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.matrictime.network.netty.protocol.message.MessageBase.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.matrictime.network.netty.protocol.message.MessageBase.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.matrictime.network.netty.protocol.message.MessageBase.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.matrictime.network.netty.protocol.message.MessageBase.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.matrictime.network.netty.protocol.message.MessageBase.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        com.matrictime.network.netty.protocol.message.MessageBase.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.matrictime.network.netty.protocol.message.MessageBase.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.matrictime.network.netty.protocol.message.MessageBase.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.matrictime.network.netty.protocol.message.MessageBase.Message.class, com.matrictime.network.netty.protocol.message.MessageBase.Message.Builder.class);
      }

      // Construct using com.matrictime.network.netty.protocol.message.MessageBase.Message.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        version_ = com.google.protobuf.ByteString.EMPTY;
        resv_ = 0;
        uMsgType_ = 0;
        uTotalLen_ = 0;
        dstRID_ = 0;
        srcRID_ = 0;
        uIndex_ = 0;
        uEncType_ = 0;
        uEncRate_ = 0;
        checkSum_ = 0;
        reqData_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.matrictime.network.netty.protocol.message.MessageBase.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public com.matrictime.network.netty.protocol.message.MessageBase.Message getDefaultInstanceForType() {
        return com.matrictime.network.netty.protocol.message.MessageBase.Message.getDefaultInstance();
      }

      @java.lang.Override
      public com.matrictime.network.netty.protocol.message.MessageBase.Message build() {
        com.matrictime.network.netty.protocol.message.MessageBase.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.matrictime.network.netty.protocol.message.MessageBase.Message buildPartial() {
        com.matrictime.network.netty.protocol.message.MessageBase.Message result = new com.matrictime.network.netty.protocol.message.MessageBase.Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.matrictime.network.netty.protocol.message.MessageBase.Message result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.version_ = version_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.resv_ = resv_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.uMsgType_ = uMsgType_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.uTotalLen_ = uTotalLen_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.dstRID_ = dstRID_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.srcRID_ = srcRID_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.uIndex_ = uIndex_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.uEncType_ = uEncType_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.uEncRate_ = uEncRate_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.checkSum_ = checkSum_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.reqData_ = reqData_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.matrictime.network.netty.protocol.message.MessageBase.Message) {
          return mergeFrom((com.matrictime.network.netty.protocol.message.MessageBase.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.matrictime.network.netty.protocol.message.MessageBase.Message other) {
        if (other == com.matrictime.network.netty.protocol.message.MessageBase.Message.getDefaultInstance()) return this;
        if (other.getVersion() != com.google.protobuf.ByteString.EMPTY) {
          setVersion(other.getVersion());
        }
        if (other.getResv() != 0) {
          setResv(other.getResv());
        }
        if (other.getUMsgType() != 0) {
          setUMsgType(other.getUMsgType());
        }
        if (other.getUTotalLen() != 0) {
          setUTotalLen(other.getUTotalLen());
        }
        if (other.getDstRID() != 0) {
          setDstRID(other.getDstRID());
        }
        if (other.getSrcRID() != 0) {
          setSrcRID(other.getSrcRID());
        }
        if (other.getUIndex() != 0) {
          setUIndex(other.getUIndex());
        }
        if (other.getUEncType() != 0) {
          setUEncType(other.getUEncType());
        }
        if (other.getUEncRate() != 0) {
          setUEncRate(other.getUEncRate());
        }
        if (other.getCheckSum() != 0) {
          setCheckSum(other.getCheckSum());
        }
        if (!other.getReqData().isEmpty()) {
          reqData_ = other.reqData_;
          bitField0_ |= 0x00000400;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                version_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 96: {
                checkSum_ = input.readInt32();
                bitField0_ |= 0x00000200;
                break;
              } // case 96
              case 256: {
                uEncRate_ = input.readInt32();
                bitField0_ |= 0x00000100;
                break;
              } // case 256
              case 272: {
                resv_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 272
              case 888: {
                uEncType_ = input.readInt32();
                bitField0_ |= 0x00000080;
                break;
              } // case 888
              case 896: {
                uIndex_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 896
              case 968: {
                dstRID_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 968
              case 986: {
                reqData_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000400;
                break;
              } // case 986
              case 1872: {
                srcRID_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 1872
              case 7840: {
                uTotalLen_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 7840
              case 7992: {
                uMsgType_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 7992
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString version_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getVersion() {
        return version_;
      }
      /**
       * <code>bytes version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        version_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }

      private int resv_ ;
      /**
       * <code>int32 resv = 34;</code>
       * @return The resv.
       */
      @java.lang.Override
      public int getResv() {
        return resv_;
      }
      /**
       * <code>int32 resv = 34;</code>
       * @param value The resv to set.
       * @return This builder for chaining.
       */
      public Builder setResv(int value) {

        resv_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 resv = 34;</code>
       * @return This builder for chaining.
       */
      public Builder clearResv() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resv_ = 0;
        onChanged();
        return this;
      }

      private int uMsgType_ ;
      /**
       * <code>int32 uMsgType = 999;</code>
       * @return The uMsgType.
       */
      @java.lang.Override
      public int getUMsgType() {
        return uMsgType_;
      }
      /**
       * <code>int32 uMsgType = 999;</code>
       * @param value The uMsgType to set.
       * @return This builder for chaining.
       */
      public Builder setUMsgType(int value) {

        uMsgType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uMsgType = 999;</code>
       * @return This builder for chaining.
       */
      public Builder clearUMsgType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uMsgType_ = 0;
        onChanged();
        return this;
      }

      private int uTotalLen_ ;
      /**
       * <code>int32 uTotalLen = 980;</code>
       * @return The uTotalLen.
       */
      @java.lang.Override
      public int getUTotalLen() {
        return uTotalLen_;
      }
      /**
       * <code>int32 uTotalLen = 980;</code>
       * @param value The uTotalLen to set.
       * @return This builder for chaining.
       */
      public Builder setUTotalLen(int value) {

        uTotalLen_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uTotalLen = 980;</code>
       * @return This builder for chaining.
       */
      public Builder clearUTotalLen() {
        bitField0_ = (bitField0_ & ~0x00000008);
        uTotalLen_ = 0;
        onChanged();
        return this;
      }

      private int dstRID_ ;
      /**
       * <code>int32 dstRID = 121;</code>
       * @return The dstRID.
       */
      @java.lang.Override
      public int getDstRID() {
        return dstRID_;
      }
      /**
       * <code>int32 dstRID = 121;</code>
       * @param value The dstRID to set.
       * @return This builder for chaining.
       */
      public Builder setDstRID(int value) {

        dstRID_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dstRID = 121;</code>
       * @return This builder for chaining.
       */
      public Builder clearDstRID() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dstRID_ = 0;
        onChanged();
        return this;
      }

      private int srcRID_ ;
      /**
       * <code>int32 srcRID = 234;</code>
       * @return The srcRID.
       */
      @java.lang.Override
      public int getSrcRID() {
        return srcRID_;
      }
      /**
       * <code>int32 srcRID = 234;</code>
       * @param value The srcRID to set.
       * @return This builder for chaining.
       */
      public Builder setSrcRID(int value) {

        srcRID_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 srcRID = 234;</code>
       * @return This builder for chaining.
       */
      public Builder clearSrcRID() {
        bitField0_ = (bitField0_ & ~0x00000020);
        srcRID_ = 0;
        onChanged();
        return this;
      }

      private int uIndex_ ;
      /**
       * <code>int32 uIndex = 112;</code>
       * @return The uIndex.
       */
      @java.lang.Override
      public int getUIndex() {
        return uIndex_;
      }
      /**
       * <code>int32 uIndex = 112;</code>
       * @param value The uIndex to set.
       * @return This builder for chaining.
       */
      public Builder setUIndex(int value) {

        uIndex_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uIndex = 112;</code>
       * @return This builder for chaining.
       */
      public Builder clearUIndex() {
        bitField0_ = (bitField0_ & ~0x00000040);
        uIndex_ = 0;
        onChanged();
        return this;
      }

      private int uEncType_ ;
      /**
       * <code>int32 uEncType = 111;</code>
       * @return The uEncType.
       */
      @java.lang.Override
      public int getUEncType() {
        return uEncType_;
      }
      /**
       * <code>int32 uEncType = 111;</code>
       * @param value The uEncType to set.
       * @return This builder for chaining.
       */
      public Builder setUEncType(int value) {

        uEncType_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uEncType = 111;</code>
       * @return This builder for chaining.
       */
      public Builder clearUEncType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        uEncType_ = 0;
        onChanged();
        return this;
      }

      private int uEncRate_ ;
      /**
       * <code>int32 uEncRate = 32;</code>
       * @return The uEncRate.
       */
      @java.lang.Override
      public int getUEncRate() {
        return uEncRate_;
      }
      /**
       * <code>int32 uEncRate = 32;</code>
       * @param value The uEncRate to set.
       * @return This builder for chaining.
       */
      public Builder setUEncRate(int value) {

        uEncRate_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>int32 uEncRate = 32;</code>
       * @return This builder for chaining.
       */
      public Builder clearUEncRate() {
        bitField0_ = (bitField0_ & ~0x00000100);
        uEncRate_ = 0;
        onChanged();
        return this;
      }

      private int checkSum_ ;
      /**
       * <code>int32 checkSum = 12;</code>
       * @return The checkSum.
       */
      @java.lang.Override
      public int getCheckSum() {
        return checkSum_;
      }
      /**
       * <code>int32 checkSum = 12;</code>
       * @param value The checkSum to set.
       * @return This builder for chaining.
       */
      public Builder setCheckSum(int value) {

        checkSum_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>int32 checkSum = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearCheckSum() {
        bitField0_ = (bitField0_ & ~0x00000200);
        checkSum_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object reqData_ = "";
      /**
       * <code>string reqData = 123;</code>
       * @return The reqData.
       */
      public java.lang.String getReqData() {
        java.lang.Object ref = reqData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reqData = 123;</code>
       * @return The bytes for reqData.
       */
      public com.google.protobuf.ByteString
          getReqDataBytes() {
        java.lang.Object ref = reqData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reqData = 123;</code>
       * @param value The reqData to set.
       * @return This builder for chaining.
       */
      public Builder setReqData(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        reqData_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>string reqData = 123;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqData() {
        reqData_ = getDefaultInstance().getReqData();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }
      /**
       * <code>string reqData = 123;</code>
       * @param value The bytes for reqData to set.
       * @return This builder for chaining.
       */
      public Builder setReqDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        reqData_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final com.matrictime.network.netty.protocol.message.MessageBase.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.matrictime.network.netty.protocol.message.MessageBase.Message();
    }

    public static com.matrictime.network.netty.protocol.message.MessageBase.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.matrictime.network.netty.protocol.message.MessageBase.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\"\307\001\n\007Message\022\017\n\007version\030\001" +
      " \001(\014\022\014\n\004resv\030\" \001(\005\022\021\n\010uMsgType\030\347\007 \001(\005\022\022\n" +
      "\tuTotalLen\030\324\007 \001(\005\022\016\n\006dstRID\030y \001(\005\022\017\n\006src" +
      "RID\030\352\001 \001(\005\022\016\n\006uIndex\030p \001(\005\022\020\n\010uEncType\030o" +
      " \001(\005\022\020\n\010uEncRate\030  \001(\005\022\020\n\010checkSum\030\014 \001(\005" +
      "\022\017\n\007reqData\030{ \001(\tB<\n-com.matrictime.netw" +
      "ork.netty.protocol.messageB\013MessageBaseb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Version", "Resv", "UMsgType", "UTotalLen", "DstRID", "SrcRID", "UIndex", "UEncType", "UEncRate", "CheckSum", "ReqData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
